# Generated by Django 5.2.16 on 2026-07-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_riskassessment_risk_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="identifier_type",
            field=models.CharField(choices=[("email", "Email address")], max_length=20),
        ),
        migrations.CreateModel(
            name="BreachFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_breach_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("breach_date", models.DateField(blank=True, null=True)),
                ("exposed_data", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_retired", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breach_findings",
                        to="assessments.riskassessment",
                    ),
                ),
            ],
        ),
    ]
